### ISSUE TITLE
Unknown version of ships won't let ships move

### ISSUE THREAD

**Issue by Batman2741** [Minecraft-Ships/ShipsForCore#100]

**Comment by mosemister** [comment]
Going to need more info then that. 

What version of Minecraft? (1.17.1? 1.19.4) 
What version of Ships? (Bukkit from dev.bukkit, Sponge from Ore or Folia from Hanger)? 
Do ships commands work? (/Ships info)
Is there a error on the console?

**Comment by mosemister** [comment]
``What version of Ships? (Bukkit from dev.bukkit, Sponge from Ore or Folia from Hanger)?``

Also what beta version of ships are you using?

**Comment by mosemister** [comment]
The latest on spigot links to to a deleted version of ships which couldnt boot, so i know your not using the that version too

**Comment by mosemister** [comment]
Closed due to no response
