### ISSUE TITLE
Water is spawned where ship was

### ISSUE THREAD

**Issue by Magiks21** [Minecraft-Ships/ShipsForCore#102]
**Describe the bug**
When moving an airship in any direction the ship is replaced by water, the ship then retakes the spaces that it moves into if water was there and any block that enters the water that can be waterlogged does.

**To Reproduce**
build airship.
Move Ship

Minecraft Version 1.19.4
Purpur-1.19.4-1979
Ships Version 6.0.0 (BETA Version 15.6)

**Log**
![2023-06-04_19 26 18](https://github.com/Minecraft-Ships/ShipsForCore/assets/2476446/574b3ced-b20a-443a-9194-5695e1b48f99)

Problem does not appear in log.

**Comment by mosemister** [comment]
Unable to replicate using bukkit supported server platforms (spigot and paper)

Can i ask if there is any water in the chunks around your ship?

**Comment by Magiks21** [comment]
There are not. This is a flatworld and I have not placed any water

**Comment by mosemister** [comment]
Got it happening on my server. Can look into it now

**Comment by mosemister** [comment]
Fixed in the latest dev build

https://github.com/Minecraft-Ships/CoreGradle/actions/runs/5188904386

Wont close until version is released
