### ISSUE TITLE
Requirement not met messages

### ISSUE THREAD

**Issue by eduardo1299** [Minecraft-Ships/ShipsForCore#103]
When i place the license sign, an error appears in the chat, it says "Cannot create your ship ontop of unknow"

Minecraft Version: 1.20.1
Software (Platform): Paper.83
Version: Ships 6.0.0 beta 15.9

**Comment by mosemister** [comment]
This message appears when your new licence sign is placed on a block that is part of another ship

**Comment by eduardo1299** [comment]
> This message appears when your new licence sign is placed on a block that is part of another ship

But there is only one ship

**Comment by mosemister** [comment]
Have you created ships before on the server?

**Comment by eduardo1299** [comment]
> Have you created ships before on the server?

Nope, its my first time testing.. 
![image](https://github.com/Minecraft-Ships/ShipsForCore/assets/113953995/1a964f3d-9e33-437b-ae17-d874af148458)
Thats my ship btw

**Comment by eduardo1299** [comment]
> > Have you created ships before on the server?
> 
> Nope, its my first time testing.. ![image](https://user-images.githubusercontent.com/113953995/254085499-1a964f3d-9e33-437b-ae17-d874af148458.png) Thats my ship btw

Its anything wrong with it? does it needs to be more pretty?

**Comment by mosemister** [comment]
Nothing wrong with the ship. 

Would you mind taking a look at the folder of 

``plugins/Ships/VesselData`` and just ensuring that there is only one file? 

Im about to go to sleep so Ill take a look tomorrow morning.

Can i also take your beta version of ships 

> Use ``/ships info`` to find out version number

**Comment by eduardo1299** [comment]
Only one file, and the beta version is 15.9

**Comment by mosemister** [comment]
Thanks. Ill take a look tomorrow morning. Can't think why that would be happening

**Comment by mosemister** [comment]
> Only one file, and the beta version is 15.9

Just looked at the code. At that point in time there should be no files as the ship isnt created. 

That file is ship data for another ship. If you open it it should have the position of the ship, from there you can track down the sign location. If its part of your ship then you can remove it and that should fix the issue

**Comment by mosemister** [comment]
This is for me. You can ignore this message

https://github.com/Minecraft-Ships/ShipsForCore/blob/a78a1d97df5536648d14871c1dc0358416c96209/src/main/java/org/ships/event/listener/CoreEventListener.java#L329

**Comment by eduardo1299** [comment]
> > Only one file, and the beta version is 15.9
> 
> Just looked at the code. At that point in time there should be no files as the ship isnt created.
> 
> That file is ship data for another ship. If you open it it should have the position of the ship, from there you can track down the sign location. If its part of your ship then you can remove it and that should fix the issue

Hello. i deleted the data, and built a new vessel, and stuff worked, except for another error. 
![image](https://github.com/Minecraft-Ships/ShipsForCore/assets/113953995/6e7fb626-163f-4a6a-bd2c-e113b8d6170c)

**Comment by eduardo1299** [comment]
And when i click the signs they keep spitting boss that says: completing block getter

**Comment by eduardo1299** [comment]
And a bunch of bars written <Unset Message> too

**Comment by eduardo1299** [comment]
They say Unset Message

**Comment by eduardo1299** [comment]
Bro this plugin is all fucked up. i got softlocked with a bunch of red errors in chat and more boss bars written unset message

**Comment by mosemister** [comment]
That sounds like its crashing in console. Would you mind uploading the crash (assuming it is) here? Using a site like pastebin?

**Comment by eduardo1299** [comment]
I don't remember right now. but ok buddy, let's try again. i'll destroy my vessels, and reinstall the plugin, and if i get any errors, i'll say it here, ok?

**Comment by mosemister** [comment]
Yep. I would like to fix any issues, not just for you but everyone who uses the Ships plugin

**Comment by eduardo1299** [comment]
Ok. first error. i just placed the license sign and a boss bar written unset message appears and doesnt get out of the screen.
![image](https://github.com/Minecraft-Ships/ShipsForCore/assets/113953995/44c6ecda-2d7d-45ea-a815-d59640aff002)

**Comment by eduardo1299** [comment]
Ok, that one bar dissapeared. but now whenever i click move or wheel sign it makes a bar written "starting blocks getter"  and when it finishes, another bar saying "checking permissions appears" and a few minutes later it disappears, and the boat doesnt move. and all the bars are a bitch to finish.

**Comment by eduardo1299** [comment]
And it also says that but no moving.
![image](https://github.com/Minecraft-Ships/ShipsForCore/assets/113953995/a3a9410c-0e56-4243-be05-c6a7ff7875b4)

**Comment by mosemister** [comment]
That sounds like a permissions issue. 

As for the bars, you can disable them using the following command

``/ships config set config bar.visible false``

Im on mobile so please use the suggestions to help you

**Comment by mosemister** [comment]
> And it also says that but no moving. ![image](https://user-images.githubusercontent.com/113953995/254366919-a3a9410c-0e56-4243-be05-c6a7ff7875b4.png)

Ok that message could be a little more helpful. Thats saying you dont meet the requirement for the ship. Add more wool or change the requirement

**Comment by eduardo1299** [comment]
More wool??? i killed my entire sheep flock and you want more wool??? isnt that enough wool??
![image](https://github.com/Minecraft-Ships/ShipsForCore/assets/113953995/4de41433-e411-40cc-9d16-e060d244f0b0)

**Comment by mosemister** [comment]
Lol. The default requirement is 20% of the whole ship should be wool. This can be lowered if you wish by a config change/command

**Comment by eduardo1299** [comment]
But isnt that way more than 20%? and the command didnt worked. 
![image](https://github.com/Minecraft-Ships/ShipsForCore/assets/113953995/b68729a6-3bb8-49ea-a2e6-a48e4bfef4d3)

**Comment by eduardo1299** [comment]
The wood part is a 3x6 grid. and the wool part is a 10x5 grid. i'm pretty sure it has more than 20%.

**Comment by mosemister** [comment]
> But isnt that way more than 20%? and the command didnt worked. ![image](https://user-images.githubusercontent.com/113953995/254368684-b68729a6-3bb8-49ea-a2e6-a48e4bfef4d3.png)

Like i said, use the suggestions to help you with the command (if your on console, assuming its supported on your console, press ``tab`` to get the suggestions)

You can increase the total percentage of wool the ship needs to be with the same config/command change if you want, just based on your message before it sounds like you wanted it lowered

**Comment by eduardo1299** [comment]
It needs to be exactly 20% or atleast 20% and how do i get to suggestions? i'm pc

**Comment by mosemister** [comment]
At least 20%

Just looked it up myself its

``Boss.Bar.Visible``

As for how, if your on minecraft as a player, its automatically done. If your on command line on your pc (CMD, terminal -> typically a black window with white text) press the ``tab`` button to get the suggestions (``tab`` is sometimes shown as two arrows ontop of eachother facing left and right)

**Comment by eduardo1299** [comment]
My god... i don't know how to do that.... everything is so complicated.. this plugin is a b to get working, i'll just get movecraft. but thanks for the patience and support.

**Comment by eduardo1299** [comment]
When i press tab it opens the player list, and do you want me to recreate my entire flock, kill them all and add more wool?

**Comment by mosemister** [comment]
Ah your on minecraft gui, that doesnt support suggestions and almost no one uses it. Sorry for assuming. 


As for what i was expecting you to do, it was just to lower the requirements to disable or put the wool requirement low. 

You can use the command of

``ships config set shiptype watership <looking this up> 0``

**Comment by eduardo1299** [comment]
Ok thanks. i'll think later if i use ships or another plugin. i need to do a lot of stuff and its getting a lot of errors...

**Comment by mosemister** [comment]
Fair enough. Everyone has different requirements in terms of what they want out of Ships. I try to meet in the middle in terms of requirements, sadly it was still too much in this case. 

Thanks for trying out ships, i might add a water ship that has no requirements by default for people like yourself
