### ISSUE TITLE
Ship dont move

### ISSUE THREAD

**Issue by TheKr1szTEN** [Minecraft-Ships/ShipsForCore#13]
Newest version
1.15.2 paperspigot

https://cdn.discordapp.com/attachments/483946565468160002/730147697125883934/unknown.png

Plugin is spam this message when i right or left click to sign

**Comment by mosemister** [comment]
Hey, are you able to turn off the server, change the setting within ships for "bossbar" to true. Boot your server and then try moving the ship, this will then tell you (and me if you send me a new image) where the ship is getting stuck.

If you could send me a image with the bar enabled that would be most helpful. Thanks

**Comment by TheKr1szTEN** [comment]
ehm, we have no problem with bossbar.
We have problem with the spam in the chat.

**Comment by mosemister** [comment]
Yes, I am aware. That message can only appear if the ship is attempting to move and you click a movement sign, therefore it means that the ship is stuck for that message to "spam" the chat. The bossbar states what stage the ship is at, therefore if the ship is stuck, it means that the bossbar will appear stuck. 

If the ship moves and the bossbar disappears, but the ship still gives this message, then please state that this is occuring.

**Comment by TheKr1szTEN** [comment]
So, where can i edit the bossbar to true? Cuz in the config there isnt bossbar: false/true option

**Comment by mosemister** [comment]
`Bar:
    Visible: true`

**Comment by TheKr1szTEN** [comment]
bossbar is on true.
Can u join to the server or add me on discord? For the quick solution.
Kr1sz#1144

**Comment by mosemister** [comment]
I cannot add you on discord, just says "your not accepting". Whats your server IP?

**Comment by TheKr1szTEN** [comment]
https://dc.trywillon.hu

**Comment by mosemister** [comment]
I get the error "Connection refused" when attempting to join that server

**Comment by TheKr1szTEN** [comment]
wait, no https. http://dc.trywillon.hu
ssl sucks

**Comment by mosemister** [comment]
I did, sorry should have said that XD. Still no luck

**Comment by TheKr1szTEN** [comment]
https://discord.gg/gFqmmV

xdddd

**Comment by mosemister** [comment]
That allows me to accept but thats it.

**Comment by mosemister** [comment]
try my discord

mosemister#0771
