### ISSUE TITLE
Ship comes up with error "The current size of your vessel is 8788, your vessel needs to be 4500 or higher"

### ISSUE THREAD

**Issue by Mp3Shark** [Minecraft-Ships/ShipsForCore#14]
Title says it all. This happens when I try to move the ship.

**info**
Minecraft version: 1.16,2
Paper-34
Version: Ships 5.0.1.14

**Comment by mosemister** [comment]
Ships 5.0.1.14 does not support any minecraft version other then MC 1.12.2 as stated on the official download. Please use Ships 6 for MC 1.13+ (including 1.16)
