### ISSUE TITLE
i made a mistake not an actual issue

### ISSUE THREAD

**Issue by Drewwalton** [Minecraft-Ships/ShipsForCore#15]

**Comment by mosemister** [comment]
How are you writing the licence sign? As in line by line. 

1) [Ships]
2) ?
3) ?
4) ?

**Comment by Drewwalton** [comment]
[Ships]
ship
name

it responds with "ship is not installed on this server"

**Comment by mosemister** [comment]
Thats odd. 
What version of Ships does it say when you do "/ships info" and what Minecraft version?

**Comment by Drewwalton** [comment]
5.0.1.14
im on 1.12.2

**Comment by mosemister** [comment]
Ah that threw me, this is the github for Ships 6. As for ships 5. Have you modified any of the config file? Also does "Ship" appear after running the command "ships developer vesseltypes"?

**Comment by Drewwalton** [comment]
oh my bad and yeah all 6 vessel types with there normal speed

**Comment by mosemister** [comment]
thats really strange, it is installed, but giving that message. mind if you send me your server IP so I can see for myself?

**Comment by Drewwalton** [comment]
sure 206.214.56.49 ill delete this after you connect

**Comment by mosemister** [comment]
got it, thanks

**Comment by mosemister** [comment]
Plugin file

`
name: Ships
version: 5.0.1.14
main: MoseShipsBukkit.Ships
permissions:
    ships.ship.use:
        description: The permission for movement of watership
        default: true
    ships.ship.make:
        description: The permission for creation of watership
        default: true
commands:
  Ships:
    usage: /ships
    description: all ships commands
`
