### ISSUE TITLE
Limit plugin to only work in certain worlds in config.yml for performance and ease of use

### ISSUE THREAD

**Issue by bitrot-alpha** [Minecraft-Ships/ShipsForCore#16]
I run a small server on PaperSpigot, and whenever I generate a timings report, Ships 6 is near the top of the list. I have like 20 worlds, all for different things. I noticed that when I unloaded the plugin, I freed up almost a gigabyte of RAM (with no players online!).

It would be really cool if I could pick which worlds I want the plugin to function in, as having an ship in SkyBlock or PvP doesn't really make sense (and would be really laggy anyway).

**Comment by mosemister** [comment]
Been in the middle of moving house, however I have just added it into the Ships code. Should be ready for the next release

**Comment by mosemister** [comment]
Fixed in beta 8.1
