### ISSUE TITLE
Dupe Items Bug

### ISSUE THREAD

**Issue by Smxxthy** [Minecraft-Ships/ShipsForCore#18]
**Describe the bug**
So, whenever you punch the move sign, if you are holding for instance a stack of netherite ingots, if you switch to a different inventory slot at the right time, it will give you another stack of netherite ingots in the slot you switched to.

**To Reproduce**
1. Punch the move sign to move.
2. A second or so before the vehicle moves, use the scroll wheel to go to another inventory slot
3. You just duped an item

**Comment by mosemister** [comment]
I will take a look at this

**Comment by mosemister** [comment]
I cannot replicate this bug. Would it be possible to send a video of it happening? or would it be easier to join your server to see it myself?

**Comment by Smxxthy** [comment]
I've recorded a video with my very sexy voice displaying the bug.
https://youtu.be/tGqjVQyJffw

**Comment by mosemister** [comment]
Thats interesting. If you enable the bossbar visibility then do the dupe bug. When you switch the item slot, what does the bossbar say on it?

Also it seems that your ships is very slow, if you want to speed that up take a look at this issue https://github.com/Minecraft-Ships/ShipsForCore/issues/17

Ill do some more testing when I can.

**Comment by Smxxthy** [comment]
First, I looked at issue #17 and checked my config, the movement and stuff was set to ships 5, and I tried ships 6 but ships 6 was actually a lot slower. Second, after enabling the boss bar in config and doing some testing, I discovered that after the boss bar says Collecting Entities: 1 (because I was the only entity in my test aircraft), I was able to switch my slot and it would dupe as soon as it moved. If I switched my slot before it said that, the duping bug didn't happen.

**Comment by mosemister** [comment]
I think i know what is going on. I will have a go. But i cannot recreate it. 

As for being slow, try beta 8 and create a new config in that. Its got a lot of new settings and changed settings, should be much faster

**Comment by Smxxthy** [comment]
I tried the beta 8 and now pretty much all of the planes I built are crippled. It keeps detecting only 1 block for each vessel I make.

**Comment by mosemister** [comment]
Thats strange. Do the following command, what does it tell you? 

/Ships config view config Advanced.Block.Track

**Comment by Smxxthy** [comment]
It says that Advanced.Block.Track is set at 4000

**Comment by mosemister** [comment]
Thats really odd then. The tracker is attempting to track a max of 4000 blocks. 

Have you got a server ip that i could join to check it out myself?

**Comment by Smxxthy** [comment]
Yeah, I prefer not to share the real IP with people on the internet (because this server is intended as a local community server for specific individuals only), so I just created a temporary IP for you. My test plane is over in the admin world (which I use for builds and stuff), so I gave you op perms, to get there once joining just do /mvtp adminworld and it should teleport you there. I set the spawn at the test plane site. **(Note: if anyone asks "who are you mosemister", don't respond, most of the players on the server are people that I know in real life and most of the players on the server expect that everyone who joins are also people who I know in real life.)**

**Server IP: str.onpointrbx.com**

**Comment by mosemister** [comment]
sorry I have been really busy, ill come on soon

**Comment by mosemister** [comment]
Hello, just visited your server, it seems like your BlockList has corrupted somehow, all materials are set to "Detect_collide"

**Comment by mosemister** [comment]
I have taken a look at your "ships:plane.messerschmitt_c1". I have attempted to use the "/ships blocklist set" command, however there is a small issue with Beta 8 whereby the command will sometimes apply the changes to a block related to the specified block in the command, so I cannot get all of it working. You will need to fix the blocklist.yml file (or have Ships recreate it)

**Comment by Smxxthy** [comment]
Alright, thanks

**Comment by Smxxthy** [comment]
I've fixed the block list, now the only issue that I have is that the plugin continues to be slow.

**Comment by mosemister** [comment]
I will take a look soon

**Comment by mosemister** [comment]
Hi, just visited your server and looked at the config values. As stated before BETA 8 has new default config values which you can find by resetting your config. After visiting your server I saw that the default config values where that of Beta 7 (or older) so I have changed the config values to the defaults that were in BETA 8 in terms of those that affect speed. I have also enabled bossbar so if the speed still isn't up to your standards, you can see what part isnt fast enough and from there I can tell you what config values relate to that potion of the movement. 

In the mean time, the Ship I attempted to use when looking at the block list is moving in (from eyeballing it) 1 second so I do hope that is to your liking, if not then there is more that can be done. The following values in the config are the ones I have changed. 

Advanced.Block.Finder: (this is the algorithm used for finding the blocks - Ships 6 causes no lag, Ships 5 is faster)
Advanced.Block.Finder.Stack.Delay: (this only applies to Ships 6 block finder algorithm - the delay between each stack)
Advanced.Block.Finder.Stack.DelayUnit: (this only applies to Ships 6 block finder algorithm - the delay between each stack)
Advanced.Block.Finder.Stack.DelayLimit: (this only applies to Ships 6 block finder algorithm - the amount of blocks within a single stack - increase this for more speed in finding blocks)
Advanced.Block.Movement: (This is the algorithm used for moving the blocks - Ships 6 causes no lag, Ships 5 is faster)
Advanced.Block.Movement.Stack.Delay:
Advanced.Block.Movement.Stack.DelayUnit: 
Advanced.Block.Movement.Stack.Limit:
Advanced.Entity.Finder.Stack.Limit: (This is what was causing your version to be so slow, this is the amount of entities Ships attempts to find on your ship at once. Before it was 2, now its 160 - increase more for more speed)

**Comment by mosemister** [comment]
Oh and just to note, your dupe Items Bug is fixed in Beta 8.2. At least should be, feel free to reopen this if it is not fixed
