### ISSUE TITLE
Burner

### ISSUE THREAD

**Issue by Duvetyn** [Minecraft-Ships/ShipsForCore#2]
I want to disable the burner for airships but can't seem to. When I turn off burners in the airship config, it still registers as "Requires Burner: Yes" in the ship info.

**Comment by mosemister** [comment]
Sorry i repied to this thread but didnt hit send for some reason.

So changing the burner value in the airship.yml will only affect the airships created after the changes, not the ones before. 

If you go into vesseldata and find the ships file (sorted by its id) you can change the burner there
