### ISSUE TITLE
Players Getting Stuck.

### ISSUE THREAD

**Issue by ColonelKai** [Minecraft-Ships/ShipsForCore#20]
**Describe the bug**
When using ship, players can get stuck on a position after moving. When a player tries to move, they get teleported back within a matter of seconds. The ship is no longer visible on /ships ship auto tab-complete.

**To Reproduce**
1. 1.16.1
2. Spigot
3. 6.0.0.0

**Log**
No.

**Comment by mosemister** [comment]
Hey. Ships can only teleport a player after the ship has fully moved and can only teleport them once per move. Is this the case? Or is it that the player will always teleport back even if the ship is no longer moving? 

As for the ship not being on the tab list anymore. Is the licence sign still on the ship?

**Comment by ColonelKai** [comment]
The player being stuck happened as following (the player is not me):
-Ship move sign click
-Ship moves
-The player gets teleported
-He is stuck
-I remove the licence
-I teleport him
-Still stuck
-I ask him to drop all his items then disconnect him, deleting the playerdata, he logs back on, i teleport him and give items, he is okay now.

**Comment by mosemister** [comment]
What was the type of ship? And is "Fall" enabled within the config?

**Comment by ColonelKai** [comment]
No, should i enable?

**Comment by mosemister** [comment]
No, I was thinking that was causing a movement that wasn't expected

was EOT enabled on the ship?

**Comment by ColonelKai** [comment]
No, it was [Move]

**Comment by mosemister** [comment]
When you say "stuck" do you mean that it would teleport that player back to the ship? Just to be sure

**Comment by ColonelKai** [comment]
At first, yes, at least until i teleported it to somewhere, after i teleported him (or killed him and he respawned) he started getting teleported to his new location instead.

**Comment by ColonelKai** [comment]
I might have a clue, standby, collecting info from players

**Comment by ColonelKai** [comment]
The issue happened again to someone that got disconnected while the ship was moving, I'm asking the previous guy if he got disconnected too.

**Comment by mosemister** [comment]
Being teleported to somewhere other then a ship on a schedule bases isn't something ships can do. Im more then happy to work out what is causing it. Let me just check Bukkits code to see if its possible to see the scheduled tasks, or something else to help work it out

**Comment by ColonelKai** [comment]
I get it confirmed that all players that experienced the bug got disconnected while the vessel was MOVING. Some with EOT some with just [MOVE].

**Comment by mosemister** [comment]
Still confused on how that happens thinking of the logic. Ill look at the code and attempt to remake it on my server

Do the players disconnect delibratly or is it because of Ships that they are disconnecting?

**Comment by ColonelKai** [comment]
Some have bad connections, one tried to relog because EOT was a little laggy

**Comment by ColonelKai** [comment]
Update:
I have realized that if players get teleported to another location by ship movement, as usual, they get unstuck.

**Comment by mosemister** [comment]
Sorry for the late reply. I am really confused on what is happening there. I got a new version of Ships coming out. Just try the new version and see if the same thing occurs, the new version has changed a lot of the translation layer which includes the scheduler. 

New version will be uploaded today, but it will need approval from dev.bukkit

**Comment by ColonelKai** [comment]
Okay, i have also realized if you move with the ship while you're stuck, it makes you unstuck. 

So probably the code that makes you float and shit while the ship moving doesn't "unfloat" you if you leave mid-process.

**Comment by mosemister** [comment]
Have a go with Beta 9.1. Been some changes to how the logon/logoff works

**Comment by ColonelKai** [comment]
Will do

**Comment by ColonelKai** [comment]
Sorry for the late reply, haven't been on my server for a while, people report that the issue still exists, just that people don't get teleported back, and they can float around wherever. Requires more testing but the server is currently down and ill write a followup.

**Comment by mosemister** [comment]
There is a update awaiting approval by the dev.bukkit (been waiting 4 days for approval ....) That fixes a lot of no gravity issues. 

Hopefully that fixes the issue for your server

**Comment by ColonelKai** [comment]
Epic, love you (no homo doe)

**Comment by mosemister** [comment]
The update is on Spigot, dev.bukkit rejected it for having code that isn't actually in it. 

https://www.spigotmc.org/resources/ships.2072/update?update=376969

**Comment by mosemister** [comment]
Closed due to inactivity
