### ISSUE TITLE
Newer blocks will not attach to ship

### ISSUE THREAD

**Issue by AteurGames** [Minecraft-Ships/ShipsForCore#26]
**Describe the bug**
Recently added blocks (such as a smoker or barrel) will not connect to the ship and will float off or collide instead.

**To Reproduce**
1. 1.14.4
2. Bukkit
3. 6.0.0.0
4. Create an OPShip with an engine sign and a smoker, barrel, loom, etc. attached to the back.
5. Use the engine sign to move forward. The block on the back will not follow the ship.

**Comment by mosemister** [comment]
Hey. Mind you send your Blocklist.yml file over? 

Blocks that are 1.14 or newer wont be detected as material blocks automatically as I havent got round to them yet (always something more pressing) however you can enable them yourself within that file

**Comment by mosemister** [comment]
Just seen your blocklist.yml from your other issue ( https://github.com/Minecraft-Ships/ShipsForCore/issues/25 ). If you wish to change the behaviour of blocks to be detected by ships, change the collide type to "material". 

Here is the exact formatting

    CollideType: MATERIAL

**Comment by AteurGames** [comment]
Thanks! I knew the blocks were configurable, but I was confused as to what about them could be changed.

**Comment by mosemister** [comment]
Sorry about the confusion. But all of them are (including modded ones)
