### ISSUE TITLE
Request for block limits in shiptype.

### ISSUE THREAD

**Issue by ColonelKai** [Minecraft-Ships/ShipsForCore#27]
since bigger ships move slower, there is not much incentive to build bigger ships, and if i could make it so giant oceanliners are faster it'd be cool :)

**Comment by mosemister** [comment]
Im confused? Are you wanting a block limit? (If so there already is) or are you wanting ships to move faster (if your server can handle it you can make them faster in the ships config)

**Comment by ColonelKai** [comment]
Oh, i didnt know, is there a documentation? I was planning on something like
*create a ship type called "Oceanliner" then make it like "at least 300 blocks"

**Comment by mosemister** [comment]
Ah your after a minimum block limit. There is something in the code that looks and reads a minimum however ships doesn't do anything with the value currently. Ill take a look at shiptype and ship data min/max values. The block limit currently is for all ships regardless of type

**Comment by ColonelKai** [comment]
aight, thanks man

**Comment by ColonelKai** [comment]
bump

**Comment by mosemister** [comment]
Hey, havent forgotten, got a huge update in the works which includes the min/max blocks. 

Sorry its taking a while, having a issue scheduling time to program Ships.

**Comment by ColonelKai** [comment]
its aight, just wondered if you were still working on Ships as a new server that uses the plugin is comin' up, and ships are one of the main ways of transportation in the giant 52gb map, so, you figure how much we need this plugin

**Comment by ColonelKai** [comment]
also i suggest opening a discord server for the plugin as people might get easier help from other people, and also its almost impossible to reach you lmao

**Comment by mosemister** [comment]
I have thought of opening a discord but the issue is what little free time i have is spent on program instead of sorting out permissions, channels, etc.

**Comment by ColonelKai** [comment]
i can do that for you

**Comment by ColonelKai** [comment]
Colonel Kai#3957 (ill delete this comment later)

**Comment by mosemister** [comment]
In beta 10 this feature is added yo both ships and types
