### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by 128912891289** [Minecraft-Ships/ShipsForCore#34]
**Describe the bug**
Whenever a bow is shot at a ship, the ship stops being able to move. At the top of the screen it also says "Collecting entities: 1". 

**To Reproduce**
1. Minecraft version (eg. 1.12.2): 1.13.2 
2. Platform (version if known) (Eg. Sponge Forge(Sponge API 7.1.0)) git-Spigot-1a3504a-e7700ab
3. Ships version (If not known then type '/ships info' Eg 6.0.0.0)  6.0.0.0 Beta 10.0 

**Log**
If applicable, add your server log to help explain your problem.
Log doesn't say anything about this.

**Comment by mosemister** [comment]
Hi. Sadly Ships 6 beta 10 only supports MC 1.16. As noted in the changed log in bold, if you wanted Ships to support older versions you need to raise your voice, so thanks for raising yours. 

https://dev.bukkit.org/projects/ships/files/3195040

**Comment by 128912891289** [comment]
Aww, man. Thanks anyway. But, you should still probably look into this issue to see if it is also happening in 1.16 since I don't think this is a version specific issue.

**Comment by mosemister** [comment]
Will do. 

Mind if I look at your ships config file? The Collecting entities is tied to the entity limit in the config

**Comment by 128912891289** [comment]
Sure! Here it is: https://gist.github.com/128912891289/adfa45cb6fd155549e8e820e427d6ea7
