### ISSUE TITLE
Async5Movement error

### ISSUE THREAD

**Issue by ThatPerkel** [Minecraft-Ships/ShipsForCore#43]
A player was moving a custom Ship (based on Marsship type) and following spam-error occured (attached below).

**SW details:**
Java 15
Paper 1.16.5 Build 629
Ships 6.0.0.0 R2 Beta 11

[error.log](https://github.com/Minecraft-Ships/ShipsForCore/files/6404191/error.log)

**Comment by mosemister** [comment]
Thats a interesting bug, it doesn't seem related to the async block finder but a error loading a ship. Perhaps there was a eariler error?

**Comment by ThatPerkel** [comment]
No, I'm afraid no error occurred prior to this bug. At least it wasn't in our log...

**Comment by mosemister** [comment]
Just uploaded beta 11.1 (awaiting approval). it should force the original error to show

**Comment by mosemister** [comment]
Closed due to lack of activity
