### ISSUE TITLE
Possible lag during player quitting

### ISSUE THREAD

**Issue by ThatPerkel** [Minecraft-Ships/ShipsForCore#44]
I've noticed that in our timings, two Ships' events are marked as laggy - PlayerQuitEvent and PlayerKickEvent. It's not currently an issue, but the timings seems quite odd (attaching below) and I'm afraid it could be a problem on a larger servers.

**SW details:**
Java 11
Paper 1.16.5 Build 629
Ships 6.0.0.0 R2 Beta 11

![image](https://user-images.githubusercontent.com/83411100/116778284-3c063c00-aa71-11eb-97e8-49497921626f.png)

**Comment by mosemister** [comment]
When the more efficent code for finding ships from a block is in then this issue should go away

**Comment by mosemister** [comment]
Should be fixed in beta 11.2

**Comment by mosemister** [comment]
Closed due to inactivity
