### ISSUE TITLE
Inefficient structure checking

### ISSUE THREAD

**Issue by ThatPerkel** [Minecraft-Ships/ShipsForCore#45]
When you enable the Structure.Update.Auto in config, the Ship gets rechecked on **every** sign click - even if you only change Speed or change altitude mode. As a result, changing  1k block ship's speed can be pretty slow (and can lag the server a lot).

**SW details:**
Java 11
Paper 1.16.5 Build 629
Ships 6.0.0.0 R2 Beta 11

**Comment by ThatPerkel** [comment]
Found out it is kinda duplicate of #22. Sorry about that.

**Comment by mosemister** [comment]
Fixed in  beta 11.2
