### ISSUE TITLE
Cannot change VaultAddon prices with new command system

### ISSUE THREAD

**Issue by ThatPerkel** [Minecraft-Ships/ShipsForCore#47]
The title is quite self-explaining; when you use the non-legacy command system, you cannot set Vaultaddon:price flag of Ships - the flag won't get recognized. In the legacy command system the flag setting works just fine.

**Comment by mosemister** [comment]
The flags command is coming to the new system, its one of the last commands to be ported

**Comment by mosemister** [comment]
Fixed in dev. Closing
