### ISSUE TITLE
Request: Adapt Watership to Changes in Sea Level

### ISSUE THREAD

**Issue by ColonelKai** [Minecraft-Ships/ShipsForCore#54]
**Is your feature request related to a problem? Please describe.**
It becomes problematic to go through canals with changing water levels, or rivers in our custom map that have changes in water level (eg. going up one block) which leaves some part of the ship submerged.

**Describe the solution you'd like**
A way for the ship to move on the Y-axis depending on the sea level.

Don't know how possible this is but, worth a shot.

**Comment by mosemister** [comment]
Its possible. Could save the waterlevel and use that. There are a few obvious issues with that though

**Comment by mosemister** [comment]
Forgot to reply to this one. 

Ships now takes the most common water level around the ship, therefore in theory when changing water level, it should adjust to the correct height
