### ISSUE TITLE
Request: Unlock looking direction on move

### ISSUE THREAD

**Issue by ColonelKai** [Minecraft-Ships/ShipsForCore#56]
**Is your feature request related to a problem? Please describe.**
My crosshair gets snapped to how I was like when I started the moving process whenever I move the ship.

**Describe the solution you'd like**
Let me look at wherever I want.

**Comment by mosemister** [comment]
This needs a change to the EntitySnapshot but should be possible

**Comment by mosemister** [comment]
This was added a while ago. Forgot to close
