### ISSUE TITLE
Move Sign claims to be moving the ship, even when it isn't.

### ISSUE THREAD

**Issue by Epicboy330** [Minecraft-Ships/ShipsForCore#57]
I had been playing around with the plugin for about 2 hours, and the move sign stopped working. For some reason, it was sensing that the ship is moving, constantly. I thought it might be if the altitude was too high, but my friends' ship worked just fine at a higher altitude. We had this problem with Marsships and Airships.

**Comment by mosemister** [comment]
Im aware of the issue, there is a command for a temporary fix. 

/ships ship <id> unlock

**Comment by mosemister** [comment]
Fixed in beta 15.3
