### ISSUE TITLE
"<Unset Message>" is displayed when interacting with move and wheel signs 

### ISSUE THREAD

**Issue by TripLea777** [Minecraft-Ships/ShipsForCore#61]
I am using a permissions plugin (light perms) to give the default rank access to all the of the ships plugins features but I have run into an issue where the control signs simply aren't working and only display "Unset Message" when pressed ( I had granted all ships permission nodes to the default rank) I am not sure if I've run into a bug or if I am doing something incorrectly, but I'd definitely appreciate some feedback.

**Comment by mosemister** [comment]
Unset message, typically means that you havent got the permissions. 

When you say you have granted all permissions, how have you done that?

**Comment by TripLea777** [comment]
> Unset message, typically means that you havent got the permissions.
> 
> When you say you have granted all permissions, how have you done that?

Originally I wanted to let players fly airships without the benefits of OP so I had installed a perms plugin to allow me to grant the permission nodes like ships.* to the default rank through the in-game commands (/lp default add ships.*) I saw confirmation that all of the ships permissions (all the ones on the main spigot page)   successfully granted but the signs still wouldnt work other  than the altitude sign. The ships were able to work for OP.

**Comment by mosemister** [comment]
Sorry for the delay. 

Its sadly a known issue that * does not work with permissions in Ships (issue with the translation layer). I am working on a fix. 

As for the permissions on the spigot form, its a bit out of date as there are formatting limitations. 

The permission to move a airship in ships 6 is. 

ships.move.ships.airship

Change the last to another shiptype to allow that. 

Sorry about the issue, its something on my lists of todos (fix permissions and update both the bukkit and spigot pages)

**Comment by TripLea777** [comment]
> Sorry for the delay.
> 
> Its sadly a known issue that * does not work with permissions in Ships (issue with the translation layer). I am working on a fix.
> 
> As for the permissions on the spigot form, its a bit out of date as there are formatting limitations.
> 
> The permission to move a airship in ships 6 is.
> 
> ships.move.ships.airship
> 
> Change the last to another shiptype to allow that.
> 
> Sorry about the issue, its something on my lists of todos (fix permissions and update both the bukkit and spigot pages)

I have entered the new permission node as well as installed a new permissions plugin and the issue seems to be fixed!
Me and my friends thank you a ton for the help and for the considerably quick responses. Have a wonderful rest of your Monday and thank you for such a fun plugin.
