### ISSUE TITLE
[PRIORITY BUG] altitude sign serious problem.

### ISSUE THREAD

**Issue by AJ552** [Minecraft-Ships/ShipsForCore#62]
In version B 6.0.0.0 R2 Beta 13.1 in Minecraft 1.17.1 "decrease" option of the [altitude] sign is selectable no more.
Please fix as soon as possible, I can't move my airship down! @mosemister @notfoundry [Video](https://cdn.discordapp.com/attachments/867893230171586560/879167405077700628/Minecraft__1.17.1_-_Multigiocatore_server_di_terze_parti_2021-08-23_02-51-41_Trim.mp4)

**Comment by mosemister** [comment]
Hello. Already passed the update for this. It's awaiting approval from dev.bukkit now

**Comment by AJ552** [comment]
Ah, thanks.
I've a question about altitude sign: how to decrease the value?
E.g.: If I want to go down of 5 Blocks I can't because the value was setted to 50 to go up.

**Comment by mosemister** [comment]
Just got approved: https://dev.bukkit.org/projects/ships/files/3434547

As for your question, if you sneak and click the sign, it will change the value (I believe it's left to increase, right to decrease), that will change the speed on the altitude sign
