### ISSUE TITLE
Wheel Bug with 1.15.2

### ISSUE THREAD

**Issue by StayCake** [Minecraft-Ships/ShipsForCore#7]
**Describe the bug**
When clicks wheel fast, it wheels only with some blocks, and there get's too much lag.

**To Reproduce**
1. Minecraft version: 1.15.2
2. Platform: paper-334
3. Ships version:

**Log**
https://pastebin.com/Nbdec4Yt

**Comment by mosemister** [comment]
Hi there. 
I will try and replicate the exact issue you have, the log you have shows that a too many actions are happening at once.

**Comment by StayCake** [comment]
But i did just move only one blocks?
either my server was 4core and 16GB ram

2020년 6월 7일 (일) 오후 6:03, Mose <notifications@github.com>님이 작성:

**Comment by mosemister** [comment]
As in your original structure was only 1 block in size? Or out of your whole structure it only moved a single block of that

**Comment by StayCake** [comment]
IDK it showed me that was 300 blocks, but that's not to be laggy.

2020년 6월 7일 (일) 오후 11:37, Mose <notifications@github.com>님이 작성:

**Comment by mosemister** [comment]
What was 300 blocks? Your ships structure?

**Comment by mosemister** [comment]
Also. What version of ships are you using? 

Use "/ships info" to check the version

**Comment by StayCake** [comment]
maybe? the plugin detects my boat structure 300 blocks, and i'm using
6.0.0.0 b4
here're some pic
[image: image.png]

2020년 6월 8일 (월) 오전 12:08, Mose <notifications@github.com>님이 작성:

**Comment by mosemister** [comment]
You images are not visible. 

Would you be able to send me your server ip? I can take a look myself then

**Comment by StayCake** [comment]
oh that's not maybe helpful cuz my server was based on korean

2020년 6월 8일 (월) 오후 11:00, Mose <notifications@github.com>님이 작성:

**Comment by mosemister** [comment]
Then I can only guess at what is happening here. 

I believe too many actions are occurring at once. Ships already has a built-in feature to stop too many actions occurring on a single ship, however, for this feature to occur, the sign that you click needs to find the ship. The method that Ships finds the sign can take a lot of resources. 

To reduce the load that the server takes, you can change the "block finder algorithm" to Ships 6 algorithm (making sure all advanced settings are set up for your server) or you can disable "auto update" on the structure which reduces the load a lot and prevents unwanted blocks from being attached to your ship, however prevents you from updating the ships structure automatically, instead you will need to manually update it by sneaking and clicking the license sign

**Comment by StayCake** [comment]
Failed to know what to do: EventListener caused exception from
org.ships.event.listener.CoreEventListener.onPlayerInteractWithBlock(AsPlayer
arg0)
[01:20:24 WARN]: java.lang.IllegalStateException: No DisplayName
[01:20:24 WARN]:        at
org.ships.implementation.bukkit.scheduler.BScheduler.<init>(BScheduler.java:46)
[01:20:24 WARN]:        at
org.ships.implementation.bukkit.scheduler.BSchedulerBuilder.build(BSchedulerBuilder.java:116)
[01:20:24 WARN]:        at
org.ships.algorthum.blockfinder.typeFinder.Ships6BlockTypeFinder.findBlock(Ships6BlockTypeFinder.java:186)
[01:20:24 WARN]:        at
org.ships.vessel.sign.MoveSign.onPrimaryClick(MoveSign.java:85)
[01:20:24 WARN]:        at
org.ships.event.listener.CoreEventListener.lambda$onPlayerInteractWithBlock$6(CoreEventListener.java:123)
[01:20:24 WARN]:        at
java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[01:20:24 WARN]:        at
java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[01:20:24 WARN]:        at
java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
[01:20:24 WARN]:        at
java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[01:20:24 WARN]:        at
java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[01:20:24 WARN]:        at
java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[01:20:24 WARN]:        at
java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown
Source)
[01:20:24 WARN]:        at
java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[01:20:24 WARN]:        at
java.util.stream.ReferencePipeline.forEach(Unknown Source)
[01:20:24 WARN]:        at
org.ships.event.listener.CoreEventListener.onPlayerInteractWithBlock(CoreEventListener.java:122)
[01:20:24 WARN]:        at
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:20:24 WARN]:        at
sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[01:20:24 WARN]:        at
sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[01:20:24 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[01:20:24 WARN]:        at
org.ships.implementation.bukkit.event.BEventLaunch.run(BEventLaunch.java:41)
[01:20:24 WARN]:        at
org.ships.implementation.bukkit.event.BukkitListener.lambda$call$2(BukkitListener.java:206)
[01:20:24 WARN]:        at java.lang.Iterable.forEach(Unknown Source)
[01:20:24 WARN]:        at
org.ships.implementation.bukkit.event.BukkitListener.call(BukkitListener.java:206)
[01:20:24 WARN]:        at
org.ships.implementation.bukkit.event.BukkitListener.onPlayerInteractWithBlockEvent(BukkitListener.java:163)
[01:20:24 WARN]:        at
com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38)
[01:20:24 WARN]:        at
co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[01:20:24 WARN]:        at
org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[01:20:24 WARN]:        at
org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[01:20:24 WARN]:        at
org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:471)
[01:20:24 WARN]:        at
net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:456)
[01:20:24 WARN]:        at
net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1413)
[01:20:24 WARN]:        at
net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
[01:20:24 WARN]:        at
net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[01:20:24 WARN]:        at
net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[01:20:24 WARN]:        at
net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[01:20:24 WARN]:        at
net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[01:20:24 WARN]:        at
net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[01:20:24 WARN]:        at
net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[01:20:24 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.ba
(MinecraftServer.java:1097)
[01:20:24 WARN]:        at
net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1090)
[01:20:24 WARN]:        at
net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[01:20:24 WARN]:        at
net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1051)
[01:20:24 WARN]:        at
net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:966)
[01:20:24 WARN]:        at java.lang.Thread.run(Unknown Source)]
I think there is some bug in 6 algorithm, and the default algorithm was set
on 5.

2020년 6월 11일 (목) 오후 11:10, Mose <notifications@github.com>님이 작성:

**Comment by StayCake** [comment]
and one more opinion.
I want the ship to be driven when it gets 2 blocks deeper in water. [or
bug?]

2020년 6월 11일 (목) 오후 11:10, Mose <notifications@github.com>님이 작성:

**Comment by mosemister** [comment]
Your crash report is reporting the issue to a line of code that no longer exists. Are you sure you are using Beta 4?

Could you go into more depth on what happens when a ship moves in water when the ship is 2 blocks deep? I am not aware of any issue with water, with the exception of having walking areas under water, which 2 blocks deep means that's unlikely the issue your referring to.

**Comment by StayCake** [comment]
I think water is caused by algorithm 5, and surely in beta 4.

2020년 6월 13일 (토) 오전 1:43, Mose <notifications@github.com>님이 작성:

**Comment by mosemister** [comment]
I have been unable to recreate your crash on beta 4. 

Please redownload and install beta 4 to your server and then restart your server

**Comment by StayCake** [comment]
Rip you made me wrong config.

here's my final opinion.
1.* please change the method name "SHIPS_6" TO "SHIPS_SIX" OR "SHIPS_FIVE"
TO "SHIPS_5" [damn rip]*
2. It's still laggy and I calculated that my boat is 622 blocks.
3. There's a bug that when I used the altitude sign, the under block and
sign were gone.

2020년 6월 13일 (토) 오전 8:02, Mose <notifications@github.com>님이 작성:

**Comment by mosemister** [comment]
1) The algorithm names do already use the number names instead of the number symbols. 

2) there is a update on its way (beta 5) which has a config option that when disabled will stop the server from lagging 

3) could you explain the bug you are having. Your lack of description makes it difficult to understand the issue your having there

**Comment by StayCake** [comment]
1. then please change to "ships_5" for default. that will make users
confused.

2 / 3. Here's a video. 3. only happens when creative.
 2020-06-15 10-37-52.mkv
<https://drive.google.com/file/d/1meo6Zm4vtYv3s_IU6bNjeVzefG6UJfu6/view?usp=drive_web>

2020년 6월 14일 (일) 오후 10:10, Mose <notifications@github.com>님이 작성:

**Comment by mosemister** [comment]
1) the standard for ids in minecraft does not allow for numbers, therefore I cannot change the name to numbers. 
With the config command giving you suggestions with the names of the numbers, the fact its in advanced options and the fact the default value uses the name of the number, i thought it was obvious. 
You will also find that changing the name will upset current users as the settings they are used to would no longer work, instead they would need to relearn the options. 

2) i dont have permission to watch that video. Can you change the settings so I can watch it, or upload it to youtube as a unlisted video?

**Comment by StayCake** [comment]
1. welp, then can you create aliaes for ship_6?

2. here's link
https://drive.google.com/file/d/1meo6Zm4vtYv3s_IU6bNjeVzefG6UJfu6/view?usp=drivesdk

2020년 6월 15일 (월) 오후 5:26, Mose <notifications@github.com>님이 작성:

**Comment by mosemister** [comment]
1) no sadly. The point of an id system is that it is unique, no 2 ids can do the same thing. 

2) sadly thats a issue with Bukkit, whereby canceling the interact with block event while the player is in creative does not cancel. Its a issue that Bukkit will not fix. 

The solution is to not move ships with creative, or to hit the signs with a sword.

**Comment by StayCake** [comment]
fine then. final opinion is optimize of algorithm

2020년 6월 16일 (화) 오후 4:04, Mose <notifications@github.com>님이 작성:

**Comment by mosemister** [comment]
Have been. In the latest release (was approved only yesterday) there is a new config option that when disabled gives much faster results. 

Also been working on async block finding, while this wont speed up the block finding algorithm, it puts it on a second thread meaning that it prevents the crash of "a server tick took too long". 

The ships 6 movement algorithm has been attempted to be updated so it only moves the blocks that actually change

Betas typically need more work and Ships 6 is still in that state
