### ISSUE TITLE
Wrong permissions for custom shiptypes

### ISSUE THREAD

**Issue by ThatPerkel** [Minecraft-Ships/ShipsForCore#73]
When you have a Custom ShipType (e.g. named 'Car', based on 'marsship'), they should have their own permissions, e.g. 'ships.move.own.ships.car'. But in the latest build, this permission is ignored and instead the parent's permission is checked (here 'ships.move.own.ships.marsship').

**Comment by mosemister** [comment]
Ah. Yep I know whats going on
