### ISSUE TITLE
Title Sign now being Recognized, and ship size keeps resetting to 0

### ISSUE THREAD

**Issue by Pioneer-Contigo** [Minecraft-Ships/ShipsForCore#77]
No matter the block or orientation of the sign, the main ship sign cannot detect any blocks. Preexisting ships suddenly have their size reduced to 0. Other signs cannot detect the main ship sign either.
This is all done on detectable MATERIAL blocks.

Minecraft ver. 1.17.1
Git-Paper-338 API ver 1.17.1
Ver. 6.0.0.0

There is no error log, no signs of error in the console, but the issue still persists.

**Comment by mosemister** [comment]
Hi sorry. Had a issue with emails and it must have not come though so sorry for the no so quick response. 

As for the issue at hand, how are you testing that the ships size goes to 0?

**Comment by mosemister** [comment]
Closed due to lack of comment
