### ISSUE TITLE
When will the plugin update to 1.8 ?

### ISSUE THREAD

**Issue by ProdigiousCraft** [Minecraft-Ships/ShipsForCore#78]
Big supporter of your work Mosmister.

Stay safe and strong !

**Comment by mosemister** [comment]
> Big supporter of your work Mosmister.
> 
> Stay safe and strong !

Hi. So it is already working on MC 1.18 (im assuming thats what you meant rather then the old 1.8) with the Ships 6 beta 14.2 update. 

Unless you mean for Sponge which is simply, its too early to say as the translation layer is still being made for Sponge. It can move ships, however the ship also remains in the old position
