### ISSUE TITLE
Ships are not moving properly

### ISSUE THREAD

**Issue by Caleston** [Minecraft-Ships/ShipsForCore#81]
**Describe the bug**
Clicking Move sign does not always move the ship and just pops up a 'Processing: Post Moving'.
Its like you have to punch the sign many times for the ship to move even once, and it still complains about having to move into water, while there is nothing but water around or 'Ships sign is already moving' when its not even moving.
Something seems to be quite broken with the Move function.
Video: [https://streamable.com/e2vd8f](https://streamable.com/e2vd8f)

MC 1.17.1
Paper-402
Ships 6.0.0 Beta 14.2

**Comment by mosemister** [comment]
This is a known issue, however it is unknown what exactly causes it (likely a crash)

**Comment by mosemister** [comment]
Fixed in beta 15.3
