### ISSUE TITLE
Throwing weird hang error when restarting server

### ISSUE THREAD

**Issue by IdekTheMaster** [Minecraft-Ships/ShipsForCore#85]
**Describe the bug**
When I try to restart my server I get the error **[06:01:56] [Server thread/ERROR]: Nag author: '<NoAuthorGiven>' of 'Ships' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.** It throws this an uncountable amount of times before the server finally shuts down

**To Reproduce**
1. Minecraft version 1.19
2. Platform (version if known) latest paper
3. Ships version 6.0.0.0

**Comment by mosemister** [comment]
Hi there. I know about the issue and have been trying to fix it. 

It's nothing to worry about as there is no data loss or anything like that

**Comment by mosemister** [comment]
Been fixed in the latest dev version. Should be in the next release
