### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by JerseyHornet** [Minecraft-Ships/ShipsForCore#87]
**Describe the bug**![image_2022-10-01_130442651](https://user-images.githubusercontent.com/90105773/193408746-0927410e-abb3-4be6-9383-7043d2acd164.png)

**Comment by mosemister** [comment]
Hi. A temporary fix for this is

``/ships ship <ship id> unlock``

**Comment by mosemister** [comment]
Fixed in beta 15.3
