### ISSUE TITLE
Not working for other players

### ISSUE THREAD

**Issue by HermannRommel** [Minecraft-Ships/ShipsForCore#89]
I installed this plugin in my server, I can used it. But when other player tried they got something like No permissions to do it

Random players try to build ship and use sign to give it definition

1. Minecraft version 1.19.3
2. Spigot
3. version 6.0.0 Beta version 15.3 Vessal type 6

nope

**Comment by mosemister** [comment]
Hi there, have you given the permissions to your regular users using your permissions plugin?

**Comment by mosemister** [comment]
This should be fixed in 15.4

**Comment by mosemister** [comment]
Closed due to no activty
