### ISSUE TITLE
Dropped Items Deleting On Ships.

### ISSUE THREAD

**Issue by TrulyTails** [Minecraft-Ships/ShipsForCore#93]
When Breaking a block or dropping an item on a defined ship the item will disappear/delete. 

_Steps to reproduce the behavior:_
Have a ship. Type tested a water ship.
Drop an item whilst standing on the ship or break a block that is a part of the ship in survival.
Items are not always deleted when dropped further away from the license sign. 
My ship of 500 blocks deletes items within 10 blocks of the sign within the ship, text facing north. 
Where as my ship of 1,180 blocks rarely deletes items.
When breaking a block the item is almost always deleted however on both ships.

Note: Throwing items onto the ship whilst not being within the defined ship will consistently drop the item on the ship properly.

1. Minecraft version: 1.19.2
2. Platform: Paper 1.19.2 server.
3. Ships version: 6.0.0, Beta Version: 15.5

No Log evidence to report.

**Comment by mosemister** [comment]
Fixed in beta 15.6 (when released)

**Comment by mosemister** [comment]
Closed due to no more comments
