### ISSUE TITLE
Console gets spammy after EOT usage. 

### ISSUE THREAD

**Issue by TrulyTails** [Minecraft-Ships/ShipsForCore#94]
Ship type used: water ship.
When enabling EOT via sign after a period of time the console gets spammy. Might be a server performance issue rather than a ships.
While in use the EOT will eventually activate twice before the set period.
Setting: Speed 30 Delay 5 seconds.
Example: Ship will go 30 blocks forward, Delay will start then go 30 blocks. Delay starts, goes 30 blocks, a shorter duration around 2-3 seconds and it will go another 30 blocks before starting the set delay, then repeat with this new "doubled" movement.
This bug also makes using signs delayed and difficult. I needed to use the command to stop the EOT. For a duration after disabling EOT the signs still had lag when trying to edit the speeds.

Unable to consistently reproduce. Seems to occur after extended usage of EOT. Console gave reports once the doubling issue above occurred. 

1. Minecraft Version 1.19.2
2. Platform: Paper 1.19.2
3. 6.0.0  beta 15.5

**Log**
[ships EOT log spam.txt](https://github.com/Minecraft-Ships/ShipsForCore/files/10518580/ships.EOT.log.spam.txt)

**Comment by mosemister** [comment]
Ah i know the issue. Ill see what i can do

**Comment by mosemister** [comment]
Fixed in beta 15.6 (when released)

**Comment by mosemister** [comment]
Closed due to no more comments
