### ISSUE TITLE
Ships latest versions make cpu ussage go 100% and sends error messages in the console, earlier stable versions get this error: "Could not pass event InventoryClickEvent to Ships v5.0.1.14"

### ISSUE THREAD

**Issue by NathanVDC-CEO-Every3D** [Minecraft-Ships/ShipsForCore#98]
I have a Minecraft server with 600 members,
I have installed ships multiple times, I have installed the versions
where the update litterally says: "Fixed 100% cpu usage isue" and it still
uses 100% of my cpu. I have tried earlier versions of Ships which are stable
but for 1.12 and I get this error message repeating in my console even 
though all the commands work fine: "Could not pass event InventoryClickEvent to Ships v5.0.1.14"

I get this error message in the new beta versions of Ships:
"Exception in thread "Thread-109" java.util.concurrent.RejectedExecutionException: java.util.concurrent.RejectedExecutionException: Thread limit exceeded replacing blocked worker"

**Comment by mosemister** [comment]
The old stable ships 5.0.1.14 doesnt work on spigots backwards compatibility for various reasons. 

As for the error. Im aware of it and actually supplied the fix in beta 15.6 however its not enabled by default. 

If you run the command of ``/ships config set config advanced.block.finder ships_six_single_async`` (im on mobile so please use the command suggestions to help you) this should fix both the crashing and cpu issues

**Comment by mosemister** [comment]
Closed due to lack of response
