### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ManG0D** [Minecraft-Ships/ShipsForCore#99]
**Describe the bug**
when trying to teleport a ship i was banned briefly in my own server for flying rejoined and am now stuck in a semi flying state i cant ascend or descend and nothing will get me out of it I've tried dying teleporting switching back and forth between game modes and nothing even uninstalling the plugin did nothing.

**To Reproduce**
Steps to reproduce the behavior: im not sure

1. Minecraft version (eg. 1.12.2) 1.19.3
2. Platform (version if known) (Eg. Sponge Forge(Sponge API 7.1.0))
3. Ships version (If not known then type '/ships info' Eg 6.0.0.0) /shipsinfo

**Log**
If applicable, add your server log to help explain your problem.

**Comment by mosemister** [comment]
This is a problem with minecraft itself. 

You need to disable "allow-flying" in the server properties. 

As for the state you are in. If you have Ships installed. You can do the following command

``/ships nogravity``
